name: Run Serenity tests and publish test report
on:
  workflow_call:
    inputs:
      test-environment:
        required: true
        type: string
  
permissions:
  contents: write
  pages: write
  id-token: write  
  
jobs:
  run_serenity_tests:
    environment:
      name: github-pages
      url: https://jpastircak.github.io/github-actions-poc/${{ github.run_number }}/    
    name: Run Serenity Tests
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Restore Maven cache
       uses: skjolber/maven-cache-github-action@v1
       with:
         step: restore 
     - name: Run Serenity tests
       run: |
          docker-compose -f docker-compose-ui.yaml up --exit-code-from tests-ui
     - name: Process JUnit test results
       uses: mikepenz/action-junit-report@v3
       if: always()
       with:
         report_paths: '**/target/site/serenity/SERENITY-JUNIT-*.xml'
     - name: Archive test report as artifact
       uses: actions/upload-artifact@v3
       with:
         name: serenity-test-report
         path: target/site/serenity/*.*
     - name: Save Maven cache
       uses: skjolber/maven-cache-github-action@v1
       with:
         step: save
     - name: Deploy
       id: deployment
       uses: peaceiris/actions-gh-pages@v3
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/site/serenity/
        destination_dir: ${{ inputs.test-environment }}/${{github.run_number}}
        keep_files: true    
      
