name: Run Serenity tests
on:
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write  
  
jobs:
  run_serenity_tests:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Run Serenity Tests
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Restore Maven cache
       uses: skjolber/maven-cache-github-action@v1
       with:
         step: restore 
     - name: Run Serenity tests
       run: |
          docker-compose -f docker-compose-ui.yaml up --exit-code-from tests-ui
     - name: Process JUnit test results
       uses: mikepenz/action-junit-report@v3
       if: always()
       with:
         report_paths: '**/target/site/serenity/SERENITY-JUNIT-*.xml'
     - name: Archive test report as artifact
       uses: actions/upload-artifact@v3
       with:
         name: serenity-test-report
         path: target/site/serenity/*.*
     - name: Save Maven cache
       uses: skjolber/maven-cache-github-action@v1
       with:
         step: save
     - name: Setup Pages
       uses: actions/configure-pages@v2
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v1
       with:
          path: 'target/site/serenity/'
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v1     
      
