name: Run Serenity tests
on:
  workflow_dispatch:
  
jobs:
  run_serenity_tests:
    name: Run Serenity Tests
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run Serenity tests
       run: |
          docker-compose -f docker-compose-ui.yaml up --exit-code-from tests-ui
     - name: Publish Serenity report
       run: |
          echo "Publishing Serenity report"
      
